#!/usr/bin/env node
// Inventory, package and verify reviewed illustrations. This does not generate images.
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const vm = require('node:vm');
const ts = require('typescript');

const root = path.resolve(__dirname, '..');
const artDir = path.join(root, 'assets/exercises');
const recordsDir = path.join(artDir, 'records');
const optimizedDir = path.join(artDir, 'optimized');
const manifestPath = path.join(artDir, 'library-manifest.json');
const registryPath = path.join(root, 'src/data/exerciseIllustrations.generated.ts');
const sha256 = bytes => crypto.createHash('sha256').update(bytes).digest('hex');
const readJson = file => JSON.parse(fs.readFileSync(file, 'utf8').replace(/^\uFEFF/, ''));
const writeJson = (file, value) => fs.writeFileSync(file, JSON.stringify(value, null, 2) + '\n');
const escapeHtml = value => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));

function readSeeds() {
    // Evaluate only the project's pure seed module after stripping TypeScript types.
    const input = fs.readFileSync(path.join(root, 'src/data/exercises.ts'), 'utf8');
    const code = ts.transpileModule(input, { compilerOptions: { module: ts.ModuleKind.CommonJS } }).outputText;
    const context = { exports: {}, Date, require: name => { throw new Error(`Unexpected seed dependency: ${name}`); } };
    vm.runInNewContext(code, context, { timeout: 5000 });
    return context.exports.SEED_EXERCISES;
}

function inventory() {
    const seeds = readSeeds();
    const seedIds = new Set(seeds.map(e => e.id));
    if (seedIds.size !== seeds.length) throw new Error('Duplicate exercise seed IDs');
    const records = new Map();
    if (fs.existsSync(recordsDir)) {
        for (const file of fs.readdirSync(recordsDir).filter(f => f.endsWith('.json'))) {
            const record = readJson(path.join(recordsDir, file));
            if (!seedIds.has(record.id) || file !== `${record.id}.json`) throw new Error(`Unknown/misnamed record: ${file}`);
            if (records.has(record.id)) throw new Error(`Duplicate record: ${record.id}`);
            records.set(record.id, record);
        }
    }
    return { seeds, records };
}

function validateSource(record) {
    if (!/^[a-z0-9-]+$/.test(record.id) || record.file !== `${record.id}.png`) throw new Error(`Invalid asset path: ${record.id}`);
    if (!record.accessibilityLabel?.trim() || !record.pose?.trim() || !record.prompt?.trim()) throw new Error(`Incomplete pose record: ${record.id}`);
    const bytes = fs.readFileSync(path.join(artDir, record.file));
    if (bytes.subarray(0, 8).toString('hex') !== '89504e470d0a1a0a') throw new Error(`Invalid PNG: ${record.id}`);
    const width = bytes.readUInt32BE(16), height = bytes.readUInt32BE(20);
    if (width !== height || width < 768) throw new Error(`Expected square source >=768px: ${record.id}`);
    if (sha256(bytes) !== record.output?.sha256?.toLowerCase() || bytes.length !== record.output?.bytes || width !== record.output?.width || height !== record.output?.height) {
        throw new Error(`Source differs from reviewed record: ${record.id}`);
    }
    return bytes;
}

function renderRegistry(entries) {
    return "// Generated by scripts/exercise-art.cjs package from independently reviewed records.\n" +
        "// Static requires ensure every listed image is bundled for offline use.\n" +
        "import type { ExerciseIllustrationAsset } from './exerciseIllustrations';\n\n" +
        'export const EXERCISE_ILLUSTRATIONS: Readonly<Record<string, ExerciseIllustrationAsset>> = {\n' +
        entries.map(e => `    '${e.id}': {\n        source: require('../../assets/exercises/${e.file}'),\n        accessibilityLabel: ${JSON.stringify(e.accessibilityLabel)},\n    },`).join('\n') + '\n};\n';
}

async function packageAssets(args) {
    const { seeds, records } = inventory();
    const approved = seeds.map(e => records.get(e.id)).filter(r => r?.review?.status === 'reviewed');
    if (args.includes('--require-complete') && approved.length !== seeds.length) throw new Error(`Only ${approved.length}/${seeds.length} independently reviewed`);
    const sharpIndex = args.indexOf('--sharp-dir');
    const sharp = sharpIndex < 0 ? require('sharp') : require(require.resolve('sharp', { paths: [path.resolve(args[sharpIndex + 1])] }));
    fs.mkdirSync(optimizedDir, { recursive: true });
    const previous = fs.existsSync(manifestPath) ? readJson(manifestPath).entries : [];
    const entries = [];
    for (const record of approved) {
        const bytes = validateSource(record);
        const sourceHash = sha256(bytes);
        const file = `optimized/${record.id}.jpg`;
        const target = path.join(artDir, file);
        const old = previous.find(e => e.id === record.id);
        if (!(old?.sourceSha256 === sourceHash && fs.existsSync(target) && sha256(fs.readFileSync(target)) === old.sha256)) {
            // Packaging only: preserve dimensions/composition; use a broadly supported opaque codec.
            await sharp(bytes).flatten({ background: '#F3F5F7' }).jpeg({ quality: 90, mozjpeg: true, chromaSubsampling: '4:4:4' }).toFile(target);
        }
        const packaged = fs.readFileSync(target);
        entries.push({ id: record.id, name: seeds.find(e => e.id === record.id).name, file, source: record.file,
            sourceSha256: sourceHash, sha256: sha256(packaged), bytes: packaged.length,
            width: record.output.width, height: record.output.height, accessibilityLabel: record.accessibilityLabel });
    }
    const manifest = { version: 1, reference: 'barbell-curl.png', totalExercises: seeds.length,
        reviewedCount: entries.length, complete: entries.length === seeds.length,
        runtimeBytes: entries.reduce((n, e) => n + e.bytes, 0), entries };
    writeJson(manifestPath, manifest);
    fs.writeFileSync(registryPath, renderRegistry(entries));
    console.log(`Packaged ${entries.length}/${seeds.length} reviewed exercises; ${(manifest.runtimeBytes / 1024 / 1024).toFixed(2)} MiB bundled.`);
}

function verify(args) {
    const { seeds, records } = inventory();
    const manifest = readJson(manifestPath);
    if (manifest.totalExercises !== seeds.length || manifest.reviewedCount !== manifest.entries.length) throw new Error('Stale manifest counts');
    if (manifest.complete !== (manifest.entries.length === seeds.length)) throw new Error('Stale manifest completeness');
    if (manifest.runtimeBytes !== manifest.entries.reduce((total, entry) => total + entry.bytes, 0)) throw new Error('Stale manifest runtime size');
    if (new Set(manifest.entries.map(e => e.id)).size !== manifest.entries.length) throw new Error('Duplicate packaged exercise');
    for (const entry of manifest.entries) {
        const record = records.get(entry.id);
        if (record?.review?.status !== 'reviewed') throw new Error(`Unreviewed packaged asset: ${entry.id}`);
        const source = validateSource(record);
        if (entry.width !== record.output.width || entry.height !== record.output.height) throw new Error(`Wrong packaged dimensions: ${entry.id}`);
        if (entry.file !== `optimized/${entry.id}.jpg` || entry.source !== record.file || entry.sourceSha256 !== sha256(source) || entry.accessibilityLabel !== record.accessibilityLabel) throw new Error(`Wrong packaged mapping: ${entry.id}`);
        const packaged = fs.readFileSync(path.join(artDir, entry.file));
        if (sha256(packaged) !== entry.sha256 || packaged.length !== entry.bytes) throw new Error(`Packaged bytes changed: ${entry.id}`);
    }
    if (fs.readFileSync(registryPath, 'utf8') !== renderRegistry(manifest.entries)) throw new Error('Registry differs from reviewed manifest');
    if (args.includes('--require-complete') && (manifest.entries.length !== seeds.length || !manifest.complete || seeds.some(e => !manifest.entries.some(a => a.id === e.id)))) throw new Error(`Incomplete library: ${manifest.entries.length}/${seeds.length}`);
    console.log(`Verified ${manifest.entries.length}/${seeds.length} mappings, reviews, source hashes and packaged assets.`);
}

function gallery() {
    const { seeds, records } = inventory();
    const cards = seeds.map(e => {
        const r = records.get(e.id), exists = r && fs.existsSync(path.join(artDir, `${e.id}.png`));
        return `<article><h2>${escapeHtml(e.name)}</h2>${exists ? `<a href="${e.id}.png"><img src="${e.id}.png" alt="${escapeHtml(r.accessibilityLabel || e.name)}" loading="lazy"></a>` : '<div class="missing">Awaiting artwork</div>'}<p>${escapeHtml(r?.review?.status || 'pending')}</p><small>${escapeHtml(e.id)}</small></article>`;
    }).join('\n');
    const reviewed = [...records.values()].filter(r => r.review?.status === 'reviewed').length;
    fs.writeFileSync(path.join(artDir, 'review.html'), `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Exercise artwork review</title><style>body{font-family:system-ui,sans-serif;margin:32px;background:#111116;color:#f5f5f7}h1{margin-bottom:4px}header{margin-bottom:24px}main{display:grid;grid-template-columns:repeat(auto-fill,minmax(300px,1fr));gap:20px}article{background:#22222a;border-radius:16px;padding:16px}h2{font-size:17px;margin:0 0 14px}img,.missing{display:block;width:100%;aspect-ratio:1;object-fit:contain;background:#f3f5f7;border-radius:9px}.missing{display:grid;place-items:center;color:#666}p,small{color:#c3c3cf}a:focus-visible{outline:3px solid #c084fc}</style><header><h1>Exercise artwork</h1><p>${reviewed} of ${seeds.length} independently reviewed. Select an image for its full-size PNG.</p></header><main>${cards}</main></html>`);
    console.log('Wrote assets/exercises/review.html');
}

async function main() {
    const [command = 'inventory', ...args] = process.argv.slice(2);
    if (command === 'package') return packageAssets(args);
    if (command === 'verify') return verify(args);
    if (command === 'gallery') return gallery();
    if (command !== 'inventory') throw new Error('Commands: inventory, package [--sharp-dir PATH] [--require-complete], verify [--require-complete], gallery');
    const { seeds, records } = inventory();
    const reviewed = seeds.filter(e => records.get(e.id)?.review?.status === 'reviewed').map(e => e.id);
    const pendingReview = seeds.filter(e => records.get(e.id)?.review?.status === 'self-reviewed').map(e => e.id);
    const pending = seeds.filter(e => !records.has(e.id)).map(e => e.id);
    console.log(JSON.stringify({ total: seeds.length, reviewed: reviewed.length, pendingReview, pending }, null, 2));
}
main().catch(error => { console.error(error.message); process.exitCode = 1; });
