// Generated by scripts/exercise-art.cjs package from independently reviewed records.
// Static requires ensure every listed image is bundled for offline use.
import type { ExerciseIllustrationAsset } from './exerciseIllustrations';

export const EXERCISE_ILLUSTRATIONS: Readonly<Record<string, ExerciseIllustrationAsset>> = {
    'bench-press-barbell': {
        source: require('../../assets/exercises/optimized/bench-press-barbell.jpg'),
        accessibilityLabel: "Flat barbell bench press at the bottom of the movement, with chest muscles highlighted.",
    },
    'bench-press-dumbbell': {
        source: require('../../assets/exercises/optimized/bench-press-dumbbell.jpg'),
        accessibilityLabel: "Flat dumbbell bench press at the bottom, with chest muscles highlighted.",
    },
    'incline-bench-press-barbell': {
        source: require('../../assets/exercises/optimized/incline-bench-press-barbell.jpg'),
        accessibilityLabel: "Incline barbell bench press at the bottom, with chest and front shoulders highlighted.",
    },
    'incline-bench-press-dumbbell': {
        source: require('../../assets/exercises/optimized/incline-bench-press-dumbbell.jpg'),
        accessibilityLabel: "Incline dumbbell bench press with chest and front shoulders highlighted.",
    },
    'chest-fly-dumbbell': {
        source: require('../../assets/exercises/optimized/chest-fly-dumbbell.jpg'),
        accessibilityLabel: "Flat dumbbell chest fly with arms open and chest muscles highlighted.",
    },
    'cable-crossover': {
        source: require('../../assets/exercises/optimized/cable-crossover.jpg'),
        accessibilityLabel: "Standing cable crossover with hands meeting in front and chest highlighted.",
    },
    'push-up': {
        source: require('../../assets/exercises/optimized/push-up.jpg'),
        accessibilityLabel: "Push-up near the bottom with hands and toes on the floor and chest highlighted.",
    },
    'dip-chest': {
        source: require('../../assets/exercises/optimized/dip-chest.jpg'),
        accessibilityLabel: "Chest dip on parallel bars with bent elbows, forward lean, and chest highlighted.",
    },
    'machine-chest-press': {
        source: require('../../assets/exercises/optimized/machine-chest-press.jpg'),
        accessibilityLabel: "Seated machine chest press with supported back and chest highlighted.",
    },
    'pec-deck': {
        source: require('../../assets/exercises/optimized/pec-deck.jpg'),
        accessibilityLabel: "Seated pec-deck fly with elbows bent against pads and chest highlighted.",
    },
    'deadlift-conventional': {
        source: require('../../assets/exercises/optimized/deadlift-conventional.jpg'),
        accessibilityLabel: "Conventional deadlift setup with the bar near the shins and back and hamstrings highlighted.",
    },
    'bent-over-row-barbell': {
        source: require('../../assets/exercises/optimized/bent-over-row-barbell.jpg'),
        accessibilityLabel: "Bent-over barbell row with the bar near the lower ribs and back muscles highlighted.",
    },
    'bent-over-row-dumbbell': {
        source: require('../../assets/exercises/optimized/bent-over-row-dumbbell.jpg'),
        accessibilityLabel: "Bent-over row with two dumbbells beside the lower ribs and back highlighted.",
    },
    'lat-pulldown': {
        source: require('../../assets/exercises/optimized/lat-pulldown.jpg'),
        accessibilityLabel: "Cable lat pulldown with an overhand bar at the upper chest and back highlighted.",
    },
    'pull-up': {
        source: require('../../assets/exercises/optimized/pull-up.jpg'),
        accessibilityLabel: "Overhand pull-up with elbows bent and back muscles highlighted.",
    },
    'chin-up': {
        source: require('../../assets/exercises/optimized/chin-up.jpg'),
        accessibilityLabel: "Underhand chin-up with elbows bent and lats and biceps highlighted.",
    },
    'seated-cable-row': {
        source: require('../../assets/exercises/optimized/seated-cable-row.jpg'),
        accessibilityLabel: "Seated cable row with the handle pulled toward the torso and back muscles highlighted.",
    },
    't-bar-row': {
        source: require('../../assets/exercises/optimized/t-bar-row.jpg'),
        accessibilityLabel: "T-bar row over an anchored bar with back muscles highlighted.",
    },
    'chest-supported-row': {
        source: require('../../assets/exercises/optimized/chest-supported-row.jpg'),
        accessibilityLabel: "Seated chest-supported machine row with bent elbows and back muscles highlighted.",
    },
    'machine-lat-pulldown': {
        source: require('../../assets/exercises/optimized/machine-lat-pulldown.jpg'),
        accessibilityLabel: "Seated machine lat pulldown with bent elbows and back muscles highlighted.",
    },
    'straight-arm-lat-pulldown': {
        source: require('../../assets/exercises/optimized/straight-arm-lat-pulldown.jpg'),
        accessibilityLabel: "Standing straight-arm rope pulldown with handles near thighs and lat muscle highlighted.",
    },
    'back-extension': {
        source: require('../../assets/exercises/optimized/back-extension.jpg'),
        accessibilityLabel: "Back extension on an angled bench, with the torso aligned with the legs and lower back and hamstrings highlighted.",
    },
    'overhead-press-barbell': {
        source: require('../../assets/exercises/optimized/overhead-press-barbell.jpg'),
        accessibilityLabel: "Standing barbell overhead press with the bar above the head and shoulders highlighted.",
    },
    'overhead-press-dumbbell': {
        source: require('../../assets/exercises/optimized/overhead-press-dumbbell.jpg'),
        accessibilityLabel: "Standing dumbbell shoulder press with bent elbows at shoulder level and shoulders highlighted.",
    },
    'lateral-raise': {
        source: require('../../assets/exercises/optimized/lateral-raise.jpg'),
        accessibilityLabel: "Standing lateral raise with dumbbells to either side and shoulders highlighted.",
    },
    'front-raise': {
        source: require('../../assets/exercises/optimized/front-raise.jpg'),
        accessibilityLabel: "Standing front raise with two dumbbells ahead at shoulder height and front shoulders highlighted.",
    },
    'rear-delt-fly': {
        source: require('../../assets/exercises/optimized/rear-delt-fly.jpg'),
        accessibilityLabel: "Bent-over dumbbell rear delt fly with arms spread and rear shoulders and mid-back highlighted.",
    },
    'face-pull': {
        source: require('../../assets/exercises/optimized/face-pull.jpg'),
        accessibilityLabel: "Standing rope face pull with hands beside the face and rear shoulders and mid-back highlighted.",
    },
    'shrug-barbell': {
        source: require('../../assets/exercises/optimized/shrug-barbell.jpg'),
        accessibilityLabel: "Standing barbell shrug with straight arms, slightly raised shoulders and upper traps highlighted.",
    },
    'shrug-dumbbell': {
        source: require('../../assets/exercises/optimized/shrug-dumbbell.jpg'),
        accessibilityLabel: "Standing dumbbell shrug with weights at sides, slightly raised shoulders and upper traps highlighted.",
    },
    'machine-shoulder-press': {
        source: require('../../assets/exercises/optimized/machine-shoulder-press.jpg'),
        accessibilityLabel: "Seated machine shoulder press with bent elbows and shoulders highlighted.",
    },
    'upright-row': {
        source: require('../../assets/exercises/optimized/upright-row.jpg'),
        accessibilityLabel: "Standing barbell upright row with elbows near shoulder height and shoulders and traps highlighted.",
    },
    'cable-lateral-raise': {
        source: require('../../assets/exercises/optimized/cable-lateral-raise.jpg'),
        accessibilityLabel: "Standing single-arm cable lateral raise with the lifting shoulder highlighted.",
    },
    'barbell-curl': {
        source: require('../../assets/exercises/optimized/barbell-curl.jpg'),
        accessibilityLabel: "Standing barbell curl midway through the lift, with an underhand grip and biceps highlighted.",
    },
    'dumbbell-curl': {
        source: require('../../assets/exercises/optimized/dumbbell-curl.jpg'),
        accessibilityLabel: "Standing dumbbell curl with palms up and biceps highlighted.",
    },
    'hammer-curl': {
        source: require('../../assets/exercises/optimized/hammer-curl.jpg'),
        accessibilityLabel: "Standing hammer curl with neutral grips, biceps and outer forearms highlighted.",
    },
    'preacher-curl': {
        source: require('../../assets/exercises/optimized/preacher-curl.jpg'),
        accessibilityLabel: "Seated preacher curl with an EZ-bar, supported upper arms and biceps highlighted.",
    },
    'cable-curl': {
        source: require('../../assets/exercises/optimized/cable-curl.jpg'),
        accessibilityLabel: "Standing cable curl with a low cable, palms up and biceps highlighted.",
    },
    'ez-bar-curl': {
        source: require('../../assets/exercises/optimized/ez-bar-curl.jpg'),
        accessibilityLabel: "Standing EZ-bar curl with angled grips and biceps highlighted.",
    },
    'incline-dumbbell-curl': {
        source: require('../../assets/exercises/optimized/incline-dumbbell-curl.jpg'),
        accessibilityLabel: "Grey mannequin seated on an incline bench curling two dumbbells, with biceps highlighted.",
    },
    'tricep-pushdown': {
        source: require('../../assets/exercises/optimized/tricep-pushdown.jpg'),
        accessibilityLabel: "Grey mannequin pressing a cable bar down in front of the thighs, with triceps highlighted.",
    },
    'tricep-dip': {
        source: require('../../assets/exercises/optimized/tricep-dip.jpg'),
        accessibilityLabel: "Grey mannequin lowering between parallel dip bars, with triceps highlighted.",
    },
    'skull-crusher': {
        source: require('../../assets/exercises/optimized/skull-crusher.jpg'),
        accessibilityLabel: "Grey mannequin lying on a flat bench lowering an EZ bar toward the forehead, with triceps highlighted.",
    },
    'close-grip-bench': {
        source: require('../../assets/exercises/optimized/close-grip-bench.jpg'),
        accessibilityLabel: "Grey mannequin pressing a barbell from the lower chest with a close grip, with chest and triceps highlighted.",
    },
    'overhead-tricep-extension': {
        source: require('../../assets/exercises/optimized/overhead-tricep-extension.jpg'),
        accessibilityLabel: "Grey mannequin holding one dumbbell behind the head during an overhead triceps extension, with triceps highlighted.",
    },
    'tricep-kickback': {
        source: require('../../assets/exercises/optimized/tricep-kickback.jpg'),
        accessibilityLabel: "Grey mannequin hinged forward extending two dumbbells behind the hips, with triceps highlighted.",
    },
    'jm-press': {
        source: require('../../assets/exercises/optimized/jm-press.jpg'),
        accessibilityLabel: "Grey mannequin on a flat bench holding a close-grip barbell above the chin with elbows raised, with triceps highlighted.",
    },
    'squat-barbell': {
        source: require('../../assets/exercises/optimized/squat-barbell.jpg'),
        accessibilityLabel: "Barbell back squat near parallel, with quadriceps highlighted.",
    },
    'front-squat': {
        source: require('../../assets/exercises/optimized/front-squat.jpg'),
        accessibilityLabel: "Grey mannequin squatting with barbell supported across front shoulders and arms crossed, with quadriceps highlighted.",
    },
    'leg-press': {
        source: require('../../assets/exercises/optimized/leg-press.jpg'),
        accessibilityLabel: "Grey mannequin seated in a sled leg press with feet on the platform and knees bent, with quadriceps highlighted.",
    },
    'leg-extension': {
        source: require('../../assets/exercises/optimized/leg-extension.jpg'),
        accessibilityLabel: "Grey mannequin extending both legs against the shin roller of a seated leg-extension machine, with quadriceps highlighted.",
    },
    'goblet-squat': {
        source: require('../../assets/exercises/optimized/goblet-squat.jpg'),
        accessibilityLabel: "Grey mannequin holding a dumbbell at the chest while squatting, with quadriceps highlighted.",
    },
    'lunge-dumbbell': {
        source: require('../../assets/exercises/optimized/lunge-dumbbell.jpg'),
        accessibilityLabel: "Grey mannequin in a forward lunge holding dumbbells at the sides, with quadriceps highlighted.",
    },
    'bulgarian-split-squat': {
        source: require('../../assets/exercises/optimized/bulgarian-split-squat.jpg'),
        accessibilityLabel: "Grey mannequin performing a split squat with rear foot supported on a bench, holding dumbbells, with quadriceps highlighted.",
    },
    'hack-squat': {
        source: require('../../assets/exercises/optimized/hack-squat.jpg'),
        accessibilityLabel: "Grey mannequin squatting in a hack-squat machine with back and shoulders supported, with quadriceps highlighted.",
    },
    'smith-machine-squat': {
        source: require('../../assets/exercises/optimized/smith-machine-squat.jpg'),
        accessibilityLabel: "Grey mannequin squatting under a Smith machine bar, with quadriceps highlighted.",
    },
    'romanian-deadlift': {
        source: require('../../assets/exercises/optimized/romanian-deadlift.jpg'),
        accessibilityLabel: "Grey mannequin holding a barbell close to the shins in a Romanian deadlift hip hinge, with hamstrings highlighted.",
    },
    'leg-curl-seated': {
        source: require('../../assets/exercises/optimized/leg-curl-seated.jpg'),
        accessibilityLabel: "Grey mannequin bending the knees against a seated leg curl machine roller, with exposed hamstrings highlighted.",
    },
    'leg-curl-lying': {
        source: require('../../assets/exercises/optimized/leg-curl-lying.jpg'),
        accessibilityLabel: "Grey mannequin lying face down and curling the heels upward against a leg curl machine roller, with hamstrings highlighted.",
    },
    'hip-thrust-barbell': {
        source: require('../../assets/exercises/optimized/hip-thrust-barbell.jpg'),
        accessibilityLabel: "Grey mannequin raising the hips beneath a padded barbell with upper back supported on a bench and feet planted.",
    },
    'glute-bridge': {
        source: require('../../assets/exercises/optimized/glute-bridge.jpg'),
        accessibilityLabel: "Grey mannequin performing a glute bridge with shoulders on the floor, knees bent and feet planted.",
    },
    'good-morning': {
        source: require('../../assets/exercises/optimized/good-morning.jpg'),
        accessibilityLabel: "Grey mannequin hinging forward with a barbell across the upper back, with hamstrings and spinal erectors highlighted.",
    },
    'hip-abductor-machine': {
        source: require('../../assets/exercises/optimized/hip-abductor-machine.jpg'),
        accessibilityLabel: "Grey mannequin seated in a hip abductor machine with knees pressing outward against pads.",
    },
    'hip-adductor-machine': {
        source: require('../../assets/exercises/optimized/hip-adductor-machine.jpg'),
        accessibilityLabel: "Grey mannequin seated in a hip adductor machine with pads against the inner thighs and adductors highlighted.",
    },
    'calf-raise-standing': {
        source: require('../../assets/exercises/optimized/calf-raise-standing.jpg'),
        accessibilityLabel: "Grey mannequin lifting the heels in a standing calf raise machine, with calf muscles highlighted.",
    },
    'calf-raise-seated': {
        source: require('../../assets/exercises/optimized/calf-raise-seated.jpg'),
        accessibilityLabel: "Grey mannequin seated with knees beneath pads and heels raised in a calf machine, with calf muscles highlighted.",
    },
    'leg-press-calf-raise': {
        source: require('../../assets/exercises/optimized/leg-press-calf-raise.jpg'),
        accessibilityLabel: "Grey mannequin extending the ankles against a leg press footplate while keeping the knees nearly straight, with calf muscles highlighted.",
    },
    'plank': {
        source: require('../../assets/exercises/optimized/plank.jpg'),
        accessibilityLabel: "Grey mannequin holding a forearm plank with a straight body line and abdominal muscles highlighted.",
    },
    'crunch': {
        source: require('../../assets/exercises/optimized/crunch.jpg'),
        accessibilityLabel: "Grey mannequin curling the shoulders off the floor in a crunch, with abdominal muscles highlighted.",
    },
    'hanging-leg-raise': {
        source: require('../../assets/exercises/optimized/hanging-leg-raise.jpg'),
        accessibilityLabel: "Grey mannequin hanging from a pull-up bar with straight legs raised forward and abdominal muscles highlighted.",
    },
    'cable-crunch': {
        source: require('../../assets/exercises/optimized/cable-crunch.jpg'),
        accessibilityLabel: "Grey mannequin kneeling at a high cable pulley and curling the torso while holding rope ends beside the head, with abdominal muscles highlighted.",
    },
    'russian-twist': {
        source: require('../../assets/exercises/optimized/russian-twist.jpg'),
        accessibilityLabel: "Grey mannequin leaning back and rotating the torso in a seated Russian twist, with abdominal muscles highlighted.",
    },
    'ab-wheel-rollout': {
        source: require('../../assets/exercises/optimized/ab-wheel-rollout.jpg'),
        accessibilityLabel: "Grey mannequin kneeling and extending forward while holding an ab wheel, with abdominal muscles highlighted.",
    },
    'sit-up': {
        source: require('../../assets/exercises/optimized/sit-up.jpg'),
        accessibilityLabel: "Grey mannequin sitting up from the floor with bent knees and arms crossed over the chest, with abdominal muscles highlighted.",
    },
    'side-plank': {
        source: require('../../assets/exercises/optimized/side-plank.jpg'),
        accessibilityLabel: "Grey mannequin holding a side plank on one forearm with feet stacked and side abdominal muscles highlighted.",
    },
    'bicycle-crunch': {
        source: require('../../assets/exercises/optimized/bicycle-crunch.jpg'),
        accessibilityLabel: "Grey mannequin performing a bicycle crunch with one knee drawn in and the opposite elbow rotated toward it, with abdominal muscles highlighted.",
    },
    'treadmill-run': {
        source: require('../../assets/exercises/optimized/treadmill-run.jpg'),
        accessibilityLabel: "Grey mannequin running on a treadmill, with exposed quadriceps, hamstrings and calf muscles highlighted.",
    },
    'outdoor-run': {
        source: require('../../assets/exercises/optimized/outdoor-run.jpg'),
        accessibilityLabel: "Outdoor running shown in a single stride, with opposite arm and leg swing.",
    },
    'stationary-bike': {
        source: require('../../assets/exercises/optimized/stationary-bike.jpg'),
        accessibilityLabel: "Seated stationary cycling with both hands on the handlebars and feet on opposite pedals.",
    },
    'outdoor-cycling': {
        source: require('../../assets/exercises/optimized/outdoor-cycling.jpg'),
        accessibilityLabel: "Outdoor cycling in a seated pedaling position, wearing a helmet and holding the handlebars.",
    },
    'rowing-machine': {
        source: require('../../assets/exercises/optimized/rowing-machine.jpg'),
        accessibilityLabel: "Rowing machine shown at the finish, legs extended and handle drawn toward the lower ribs.",
    },
    'elliptical': {
        source: require('../../assets/exercises/optimized/elliptical.jpg'),
        accessibilityLabel: "Elliptical trainer shown mid-stride with feet on the pedals and hands holding the paired handles.",
    },
    'stair-climber': {
        source: require('../../assets/exercises/optimized/stair-climber.jpg'),
        accessibilityLabel: "Stair climber shown while stepping upward, with one foot on the higher step and hands lightly on the rails.",
    },
    'jump-rope': {
        source: require('../../assets/exercises/optimized/jump-rope.jpg'),
        accessibilityLabel: "Jump rope shown in a small two-foot hop with the rope arcing overhead.",
    },
    'battle-ropes': {
        source: require('../../assets/exercises/optimized/battle-ropes.jpg'),
        accessibilityLabel: "Battle ropes shown during an alternating wave, with knees softly bent and one hand higher than the other.",
    },
    'box-jumps': {
        source: require('../../assets/exercises/optimized/box-jumps.jpg'),
        accessibilityLabel: "Box jump shown at landing on a low box, with both feet supported and knees bent.",
    },
    'burpees': {
        source: require('../../assets/exercises/optimized/burpees.jpg'),
        accessibilityLabel: "Burpee shown in the crouched transition, hands on the floor and feet drawn toward the hands.",
    },
    'mountain-climbers': {
        source: require('../../assets/exercises/optimized/mountain-climbers.jpg'),
        accessibilityLabel: "Mountain climber shown with hands planted in a high plank and one knee drawn toward the chest.",
    },
    'jumping-jacks': {
        source: require('../../assets/exercises/optimized/jumping-jacks.jpg'),
        accessibilityLabel: "Jumping jack shown in the open position, with feet apart and arms raised overhead.",
    },
    'high-knees': {
        source: require('../../assets/exercises/optimized/high-knees.jpg'),
        accessibilityLabel: "High knees shown with one thigh lifted near horizontal and the opposite arm forward.",
    },
    'hamstring-stretch': {
        source: require('../../assets/exercises/optimized/hamstring-stretch.jpg'),
        accessibilityLabel: "Seated hamstring stretch with one leg extended and the torso gently hinging toward it.",
    },
    'quad-stretch': {
        source: require('../../assets/exercises/optimized/quad-stretch.jpg'),
        accessibilityLabel: "Standing quadriceps stretch holding one ankle behind the body with knees close together.",
    },
    'chest-stretch': {
        source: require('../../assets/exercises/optimized/chest-stretch.jpg'),
        accessibilityLabel: "Standing chest stretch with hands clasped behind the hips and the chest gently opened.",
    },
    'shoulder-stretch': {
        source: require('../../assets/exercises/optimized/shoulder-stretch.jpg'),
        accessibilityLabel: "Cross-body shoulder stretch with the opposite hand supporting the upper arm above the elbow.",
    },
    'hip-flexor-stretch': {
        source: require('../../assets/exercises/optimized/hip-flexor-stretch.jpg'),
        accessibilityLabel: "Half-kneeling hip flexor stretch with the back knee supported on a mat and front foot planted.",
    },
    'pigeon-pose': {
        source: require('../../assets/exercises/optimized/pigeon-pose.jpg'),
        accessibilityLabel: "Pigeon stretch with the front knee bent, rear leg extended back and hands supporting an upright torso.",
    },
    'cat-cow-stretch': {
        source: require('../../assets/exercises/optimized/cat-cow-stretch.jpg'),
        accessibilityLabel: "Cat-cow mobility shown in the cat phase, on hands and knees with the back gently rounded.",
    },
    'dumbbell-floor-press': {
        source: require('../../assets/exercises/optimized/dumbbell-floor-press.jpg'),
        accessibilityLabel: "Dumbbell floor press at the bottom, with knees bent, feet planted and upper arms on the floor.",
    },
    'dumbbell-romanian-deadlift': {
        source: require('../../assets/exercises/optimized/dumbbell-romanian-deadlift.jpg'),
        accessibilityLabel: "Dumbbell Romanian deadlift in a hip hinge, with slightly bent knees and weights close to the shins.",
    },
    'dumbbell-goblet-squat': {
        source: require('../../assets/exercises/optimized/dumbbell-goblet-squat.jpg'),
        accessibilityLabel: "Dumbbell goblet squat near parallel, holding one vertical dumbbell close to the chest with heels planted.",
    },
    'kettlebell-goblet-squat': {
        source: require('../../assets/exercises/optimized/kettlebell-goblet-squat.jpg'),
        accessibilityLabel: "Kettlebell goblet squat near parallel, holding the bell by both horns at the chest with heels planted.",
    },
    'kettlebell-deadlift': {
        source: require('../../assets/exercises/optimized/kettlebell-deadlift.jpg'),
        accessibilityLabel: "Kettlebell deadlift near the floor, with both hands on one bell, hips back and feet planted.",
    },
    'kettlebell-row': {
        source: require('../../assets/exercises/optimized/kettlebell-row.jpg'),
        accessibilityLabel: "Kettlebell row with a staggered stance, free hand on the front thigh and the working elbow pulled toward the hip.",
    },
    'resistance-band-row': {
        source: require('../../assets/exercises/optimized/resistance-band-row.jpg'),
        accessibilityLabel: "Seated resistance band row with softly bent knees, band looped around both feet and hands pulled toward the waist.",
    },
    'bodyweight-squat': {
        source: require('../../assets/exercises/optimized/bodyweight-squat.jpg'),
        accessibilityLabel: "Bodyweight squat near parallel, with feet planted and arms extended forward for balance.",
    },
    'reverse-lunge-bodyweight': {
        source: require('../../assets/exercises/optimized/reverse-lunge-bodyweight.jpg'),
        accessibilityLabel: "Bodyweight reverse lunge at the bottom, with the front foot planted, rear heel lifted and rear knee hovering above the floor.",
    },
    'pike-push-up': {
        source: require('../../assets/exercises/optimized/pike-push-up.jpg'),
        accessibilityLabel: "Pike push-up with hips raised, elbows bent and head lowered toward the floor between the hands.",
    },
    'hamstring-walkout': {
        source: require('../../assets/exercises/optimized/hamstring-walkout.jpg'),
        accessibilityLabel: "Hamstring walkout shown with hips lifted, heels extended away from the body and arms resting on the floor.",
    },
    'bodyweight-calf-raise': {
        source: require('../../assets/exercises/optimized/bodyweight-calf-raise.jpg'),
        accessibilityLabel: "Bodyweight calf raise at the top, with both heels lifted and weight supported on the forefeet.",
    },
    'prone-y-raise': {
        source: require('../../assets/exercises/optimized/prone-y-raise.jpg'),
        accessibilityLabel: "Prone Y raise with the torso supported on the floor and arms lifted slightly overhead in a Y, thumbs pointing up.",
    },
    'brisk-walk': {
        source: require('../../assets/exercises/optimized/brisk-walk.jpg'),
        accessibilityLabel: "Brisk walking with the front heel touching down, rear forefoot pushing off and arms swinging opposite the legs.",
    },
    'calf-stretch': {
        source: require('../../assets/exercises/optimized/calf-stretch.jpg'),
        accessibilityLabel: "Standing calf stretch with the rear leg straight and heel planted, the front knee bent and hands resting on the front thigh.",
    },
    'thoracic-rotation': {
        source: require('../../assets/exercises/optimized/thoracic-rotation.jpg'),
        accessibilityLabel: "Side-lying thoracic rotation with hips and knees bent together, lower arm forward and upper arm opened behind as the chest turns upward.",
    },
    'standing-cat-cow': {
        source: require('../../assets/exercises/optimized/standing-cat-cow.jpg'),
        accessibilityLabel: "Standing cat-cow shown in the rounded-back phase, with knees softly bent and hands resting on the thighs.",
    },
};
